//------------------------------------------------------------------------------
// <auto-generated>
//		 This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//		 version 1.7.0
//		 from Assets/InputManager/PlayerInputActions.inputactions
//
//		 Changes to this file may cause incorrect behavior and will be lost if
//		 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
		public InputActionAsset asset { get; }
		public @PlayerInputActions()
		{
				asset = InputActionAsset.FromJson(@"{
		""name"": ""PlayerInputActions"",
		""maps"": [
				{
						""name"": ""Player"",
						""id"": ""96029844-e04b-47a4-8834-9ec932d3d074"",
						""actions"": [
								{
										""name"": ""Move"",
										""type"": ""Value"",
										""id"": ""0a8274fc-8d53-4ddc-b6a6-50e3c17b8115"",
										""expectedControlType"": ""Vector2"",
										""processors"": """",
										""interactions"": """",
										""initialStateCheck"": true
								},
								{
										""name"": ""Jump"",
										""type"": ""Button"",
										""id"": ""a62c7641-2e12-4f71-bcca-19917a893c34"",
										""expectedControlType"": ""Button"",
										""processors"": """",
										""interactions"": """",
										""initialStateCheck"": false
								},
								{
										""name"": ""Sprint"",
										""type"": ""Button"",
										""id"": ""e88f5993-85ec-4c63-9fe4-c43fd9b4c36d"",
										""expectedControlType"": ""Button"",
										""processors"": """",
										""interactions"": """",
										""initialStateCheck"": false
								},
								{
										""name"": ""Interact"",
										""type"": ""Button"",
										""id"": ""66fdb852-c5f7-4a74-ae0f-9da9970d75db"",
										""expectedControlType"": ""Button"",
										""processors"": """",
										""interactions"": """",
										""initialStateCheck"": false
								}
						],
						""bindings"": [
								{
										""name"": ""2D Vector"",
										""id"": ""2bafeed7-5f52-4afc-9ae4-b778235d2935"",
										""path"": ""2DVector"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Move"",
										""isComposite"": true,
										""isPartOfComposite"": false
								},
								{
										""name"": ""up"",
										""id"": ""662aead4-2126-44a1-8ea3-3153ffc15697"",
										""path"": ""<Keyboard>/w"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Move"",
										""isComposite"": false,
										""isPartOfComposite"": true
								},
								{
										""name"": ""down"",
										""id"": ""4be74702-a517-40d8-ae78-b2a034553169"",
										""path"": ""<Keyboard>/s"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Move"",
										""isComposite"": false,
										""isPartOfComposite"": true
								},
								{
										""name"": ""left"",
										""id"": ""f5af835f-fb3c-43be-a1c1-cdb337d0efb1"",
										""path"": ""<Keyboard>/a"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Move"",
										""isComposite"": false,
										""isPartOfComposite"": true
								},
								{
										""name"": ""right"",
										""id"": ""f5cd98cb-f0f1-4fa4-88be-cb76d3414b13"",
										""path"": ""<Keyboard>/d"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Move"",
										""isComposite"": false,
										""isPartOfComposite"": true
								},
								{
										""name"": """",
										""id"": ""5c6bfeea-35a0-4923-821c-f9859e0c4169"",
										""path"": ""<Keyboard>/space"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Jump"",
										""isComposite"": false,
										""isPartOfComposite"": false
								},
								{
										""name"": """",
										""id"": ""3bab3413-d51b-426c-9569-2ce2614764c1"",
										""path"": ""<Keyboard>/leftShift"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Sprint"",
										""isComposite"": false,
										""isPartOfComposite"": false
								},
								{
										""name"": """",
										""id"": ""63859b25-dfb6-4079-96d7-850d6d25a461"",
										""path"": ""<Keyboard>/f"",
										""interactions"": """",
										""processors"": """",
										""groups"": """",
										""action"": ""Interact"",
										""isComposite"": false,
										""isPartOfComposite"": false
								}
						]
				}
		],
		""controlSchemes"": []
}");
				// Player
				m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
				m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
				m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
				m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
				m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
		}

		public void Dispose()
		{
				UnityEngine.Object.Destroy(asset);
		}

		public InputBinding? bindingMask
		{
				get => asset.bindingMask;
				set => asset.bindingMask = value;
		}

		public ReadOnlyArray<InputDevice>? devices
		{
				get => asset.devices;
				set => asset.devices = value;
		}

		public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

		public bool Contains(InputAction action)
		{
				return asset.Contains(action);
		}

		public IEnumerator<InputAction> GetEnumerator()
		{
				return asset.GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
				return GetEnumerator();
		}

		public void Enable()
		{
				asset.Enable();
		}

		public void Disable()
		{
				asset.Disable();
		}

		public IEnumerable<InputBinding> bindings => asset.bindings;

		public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
		{
				return asset.FindAction(actionNameOrId, throwIfNotFound);
		}

		public int FindBinding(InputBinding bindingMask, out InputAction action)
		{
				return asset.FindBinding(bindingMask, out action);
		}

		// Player
		private readonly InputActionMap m_Player;
		private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
		private readonly InputAction m_Player_Move;
		private readonly InputAction m_Player_Jump;
		private readonly InputAction m_Player_Sprint;
		private readonly InputAction m_Player_Interact;
		public struct PlayerActions
		{
				private @PlayerInputActions m_Wrapper;
				public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
				public InputAction @Move => m_Wrapper.m_Player_Move;
				public InputAction @Jump => m_Wrapper.m_Player_Jump;
				public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
				public InputAction @Interact => m_Wrapper.m_Player_Interact;
				public InputActionMap Get() { return m_Wrapper.m_Player; }
				public void Enable() { Get().Enable(); }
				public void Disable() { Get().Disable(); }
				public bool enabled => Get().enabled;
				public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
				public void AddCallbacks(IPlayerActions instance)
				{
						if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
						m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
						@Move.started += instance.OnMove;
						@Move.performed += instance.OnMove;
						@Move.canceled += instance.OnMove;
						@Jump.started += instance.OnJump;
						@Jump.performed += instance.OnJump;
						@Jump.canceled += instance.OnJump;
						@Sprint.started += instance.OnSprint;
						@Sprint.performed += instance.OnSprint;
						@Sprint.canceled += instance.OnSprint;
						@Interact.started += instance.OnInteract;
						@Interact.performed += instance.OnInteract;
						@Interact.canceled += instance.OnInteract;
				}

				private void UnregisterCallbacks(IPlayerActions instance)
				{
						@Move.started -= instance.OnMove;
						@Move.performed -= instance.OnMove;
						@Move.canceled -= instance.OnMove;
						@Jump.started -= instance.OnJump;
						@Jump.performed -= instance.OnJump;
						@Jump.canceled -= instance.OnJump;
						@Sprint.started -= instance.OnSprint;
						@Sprint.performed -= instance.OnSprint;
						@Sprint.canceled -= instance.OnSprint;
						@Interact.started -= instance.OnInteract;
						@Interact.performed -= instance.OnInteract;
						@Interact.canceled -= instance.OnInteract;
				}

				public void RemoveCallbacks(IPlayerActions instance)
				{
						if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
								UnregisterCallbacks(instance);
				}

				public void SetCallbacks(IPlayerActions instance)
				{
						foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
								UnregisterCallbacks(item);
						m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
						AddCallbacks(instance);
				}
		}
		public PlayerActions @Player => new PlayerActions(this);
		public interface IPlayerActions
		{
				void OnMove(InputAction.CallbackContext context);
				void OnJump(InputAction.CallbackContext context);
				void OnSprint(InputAction.CallbackContext context);
				void OnInteract(InputAction.CallbackContext context);
		}
}
